# celpy doesn't support nano seconds
# ref: https://github.com/cloud-custodian/cel-python/issues/43
standard_constraints/well_known_types/duration:
 - gte_lte/invalid/above
 - lte/invalid
 - not in/valid
standard_constraints/well_known_types/timestamp:
 - gte_lte/invalid/above
 - lte/invalid

library/is_ip:
  - version/omitted/invalid/ipv6/g
  #       input: [type.googleapis.com/buf.validate.conformance.cases.IsIp]:{val:":0::0"}
  #        want: validation error (1 violation)
  #          1. constraint_id: "library.is_ip"
  #         got: valid
  - version/omitted/invalid/ipv6/h
  #       input: [type.googleapis.com/buf.validate.conformance.cases.IsIp]:{val:"0::0:"}
  #        want: validation error (1 violation)
  #          1. constraint_id: "library.is_ip"
  #         got: valid
  - version/omitted/invalid/ipv6/i
  #       input: [type.googleapis.com/buf.validate.conformance.cases.IsIp]:{val:"0::0:"}
  #        want: validation error (1 violation)
  #          1. constraint_id: "library.is_ip"
  #         got: valid
  - version/omitted/invalid/ipv6/j
  #       input: [type.googleapis.com/buf.validate.conformance.cases.IsIp]:{val:"::0000ffff"}
  #        want: validation error (1 violation)
  #          1. constraint_id: "library.is_ip"
  #         got: unexpected error: string index out of range
